load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "go_default_library",
    srcs = ["utils.go"],
    importpath = "github.com/bazelbuild/rules_docker/container/go/pkg/utils",
    visibility = ["//visibility:public"],
)
