package(default_visibility = ["//visibility:public"])

py_binary(
    name = "config_stripper",
    srcs = ["config_stripper.py"],
)

exports_files([
    "commit.sh.tpl",
    "extract.sh.tpl",
    "image_util.sh",
])
