FROM gcr.io/cloud-marketplace/google/ubuntu1604:latest

RUN \
  apt-get update && \
  apt-get install -y openjdk-8-jdk python python-dev python-pip python-virtualenv && \
  rm -rf /var/lib/apt/lists/*
