# Copyright 2017 The Bazel Authors. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
package(default_visibility = ["//visibility:public"])

licenses(["notice"])  # Apache 2.0

load("@bazel_skylib//:skylark_library.bzl", "skylark_library")

skylark_library(
    name = "filetype",
    srcs = ["filetype.bzl"],
)

skylark_library(
    name = "label",
    srcs = ["label.bzl"],
)

skylark_library(
    name = "path",
    srcs = ["path.bzl"],
)

skylark_library(
    name = "serialize",
    srcs = ["serialize.bzl"],
)

skylark_library(
    name = "zip",
    srcs = ["zip.bzl"],
)
